site_name: Gopher MCP
site_description: A cross-platform Model Context Protocol (MCP) server for browsing Gopher resources
site_url: https://cameronrye.github.io/gopher-mcp
repo_url: https://github.com/cameronrye/gopher-mcp
repo_name: cameronrye/gopher-mcp
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

nav:
  - Home: index.md
  - Installation: installation.md
  - API Reference: api-reference.md
  - Advanced Features: advanced-features.md
  - AI Assistant Guide: ai-assistant-guide.md
  - Protocols:
      - Gopher Specification: gopher-specification-for-llms.md
      - Gemini Support: gemini-support.md
      - Gemini Configuration: gemini-configuration.md
      - Gemini Specification: gemini-specification-for-llms.md
      - Gemini Troubleshooting: gemini-troubleshooting.md
  - Guides:
      - Migration Guide: migration-guide.md
      - Task Runner: task-runner.md
  - Development:
      - Repository Setup: development/repository-setup.md
      - Open Source Release Checklist: development/open-source-release-checklist.md
      - Gemini API Contracts: development/gemini_api_contracts.md
      - Gemini Project Timeline: development/gemini_project_timeline.md
      - Gemini Security Architecture: development/gemini_security_architecture.md
  - Contributing: contributing.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "pymdownx.superfences.fence_code_format"
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cameronrye/gopher-mcp
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/gopher-mcp/
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2025 Gopher MCP Team
