blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://cameronrye.github.io/gopher-mcp
    about: Check the documentation for guides and API reference
  - name: 💬 Discussions
    url: https://github.com/cameronrye/gopher-mcp/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/cameronrye/gopher-mcp/security/advisories/new
    about: Report security vulnerabilities privately
