name: ❓ Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question about the Gopher MCP Server? We're here to help!

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before asking your question
      options:
        - label: I have searched existing issues to see if my question has been answered already
          required: true
        - label: I have read the [documentation](https://cameronrye.github.io/gopher-mcp)
          required: true
        - label: I have checked the [FAQ section](https://cameronrye.github.io/gopher-mcp) if available
          required: false

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What category does your question fall into?
      options:
        - Installation & Setup
        - Configuration
        - Usage & Features
        - Troubleshooting
        - Development & Contributing
        - Protocol Specifications
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please describe your question in detail...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context that might help us answer your question
      placeholder: |
        - What are you trying to achieve?
        - What have you tried so far?
        - Any relevant configuration or setup details?

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: If your question is environment-specific, please provide details
      placeholder: |
        - OS: [e.g., Windows 11, macOS 14, Ubuntu 22.04]
        - Python version: [e.g., 3.11.5]
        - gopher-mcp version: [e.g., 0.1.0]
